# Generated by Django 4.0.2 on 2022-02-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3)),
                ('time', models.TimeField()),
                ('rounds', models.SmallIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordSearchGame_PythonDjango.words')),
            ],
        ),
    ]
